run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - goconst
    - gocyclo
    - misspell
    - nolintlint

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G204 # Subprocess launched with variable (expected for Docker CLI)
      - G304 # File path provided as taint input (expected for file operations)

issues:
  exclude-dirs:
    - native
    - embedded
  max-issues-per-linter: 50
  max-same-issues: 10
