version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ccbox
    main: ./cmd/ccbox
    binary: ccbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sungur/ccbox/internal/cli.Version={{.Version}}
      - -X github.com/sungur/ccbox/internal/cli.Commit={{.Commit}}
      - -X github.com/sungur/ccbox/internal/cli.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "ccbox_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: sungur
    name: ccbox
  prerelease: auto
